# Generated by Django 4.2.25 on 2025-10-31 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cart_cartstatus_delivery_deliverystatus_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='output',
            name='order',
        ),
        migrations.RemoveField(
            model_name='output',
            name='product',
        ),
        migrations.RemoveField(
            model_name='output',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.DeleteModel(
            name='Input',
        ),
        migrations.DeleteModel(
            name='Output',
        ),
        migrations.DeleteModel(
            name='OutputReason',
        ),
    ]
