# Generated by Django 4.2.24 on 2025-11-15 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_order_options_order_comprobante_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='core.deliverystatus', verbose_name='Estado de entrega'),
        ),
    ]
