# Generated by Django 4.2.24 on 2025-10-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0002_remove_user_is_active_user__is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin', 'Administrador'), ('cliente', 'Cliente')], default='cliente', max_length=20),
        ),
    ]
