# Generated by Django 4.2.25 on 2025-10-31 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0004_alter_user_address_alter_user_city_and_more'),
        ('auth_users', '0004_remove_user_role_alter_user_address_alter_user_city_and_more'),
    ]

    operations = [
    ]
