# Generated by Django 4.2.25 on 2025-10-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0005_merge_20251031_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='¿Puede entrar al administrador?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='¿Es súper Usuario?'),
        ),
    ]
