"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import dj_database_url  
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = config('SECRET_KEY')

DEBUG = config('DEBUG',default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())

# Application definition

INSTALLED_APPS = [
    'jazzmin', #agregando libreria jazmin  27-9-25
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'auth_users',
    'abcstracts',
    'core'
]


JAZZMIN_SETTINGS = {
    # Titulo de la ventana
    "site_title": "PanLyR Admin",
    "site_header": "🍞 PanLyR",
    # Para el nombre del menu
    "site_brand": "PanLyR",
    "site_logo" : "/auth_users/img/logo.jpg",
    "login_logo" : "/auth_users/img/logo.jpg",
    # Clase css que se aplica al logotipo de arriba
    "site_logo_classes": "img-circle",
    # Testo de bienvenida en la pantalla de inicio de seción
    "welcome_sign": "Es un gusto tenerte de nuevo aqui!!!",
    "custom_css": "admin/css/custom.css",  # archivo de estilos para admin
    "copyright" : "Presentado como proyecto para la universidad",


    "search_model": ["auth_users.User", "core.Product", "core.Delivery"],
    # cambiar los iconos de las apps y modelos en la barra lateral ya jazzmin los tiene incorporados
    "icons": {
    "auth_users.User": "fas fa-user-shield",       # Usuario
    "core.Product": "fas fa-bread-slice",          # Productos
    "core.Category": "fas fa-tags",                # Categorías
    "core.PaymentMethod": "fas fa-credit-card",    # Métodos de pago
    "core.CartStatus": "fas fa-shopping-basket",   # Estado de carrito
    "core.OrderType": "fas fa-list-alt",           # Tipo de pedido
    "core.DeliveryStatus": "fas fa-truck",         # Estado de entrega
    "core.OutputReason": "fas fa-exclamation",     # Motivo de salida
    "core.Cart": "fas fa-shopping-cart",           # Carrito
    "core.CartProduct": "fas fa-box-open",         # Producto en carrito
    "core.Payment": "fas fa-money-bill-wave",      # Pagos
    "core.Delivery": "fas fa-shipping-fast",       # Entregas
    "core.Order": "fas fa-clipboard-list",         # Pedidos
    "core.Input": "fas fa-arrow-down",             # Entradas
    "core.Output": "fas fa-arrow-up",
    "auth.Group": "fas fa-users",  # 👈 icono para grupos 
    },


    
    
    

    "show_ui_builder": True #Para tema claro y oscuro
}


JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-warning",
    "accent": "accent-navy",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-light-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "materia",
    "dark_mode_theme": "solar",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'configs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], #folder templates global
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.cart_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'configs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.parse(config('DATABASE_URL'))
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

#LANGUAGE_CODE = 'en-us'

#TIME_ZONE = 'UTC'

#USE_I18N = True

#USE_TZ = True

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Caracas'  # Ajusta según tu ubicación

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "core" / "static"]


MEDIA_URL = '/media/' 
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'auth_users.User'

